HackerNewsApp/config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts, only: [:new, :index, :create]
  resources :users, only: [:new, :create, :show]
  get '/login', to: 'users#login'
  get '/logout', to: 'users#logout'
  post '/loginn', to: 'users#loginn'
  post '/user_posts', to: 'posts#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

HackerNewsApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

HackerNewsApp/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

HackerNewsApp/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

HackerNewsApp/app/models/user.rb
class User < ApplicationRecord

  has_many :posts

  validates :username, presence: true, uniqueness: true

  has_secure_password
end

HackerNewsApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

HackerNewsApp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

HackerNewsApp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(params[:format]) # this feels dirty... if i used a declared resource
    # instead of current_user it would have recognized :resource_id right?
    @post = @user.posts.new(post_params)

    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :url)
    end
end

HackerNewsApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def login
    @user = User.new
  end

  def loginn
    # binding.pry
    @user = User.find_by(username: user_params[:username])
    if @user
      if @user.authenticate(user_params[:password])
        session[:user_id] = @user.id
        redirect_to root_path
      else
        @password_error = true
        render 'login'
      end
    else
      @username_error = true
      render 'login'
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end

  def show
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

HackerNewsApp/app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!current_user
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

HackerNewsApp/app/helpers/comments_helper.rb
module CommentsHelper
end

HackerNewsApp/app/helpers/post_helper.rb
module PostHelper
end

HackerNewsApp/app/helpers/users_helper.rb
module UsersHelper
end

HackerNewsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNewsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <ul>
        <% if logged_in? %>
          <li>
            <%= link_to current_user.username, user_path(current_user)  %>
          </li>
          <li>
            <%= link_to "Logout", logout_path %>
          </li>
        <% else %>
          <li>
            <%= link_to "Register", new_user_path %>
          </li>
          <li>
            <%= link_to "Login", login_path  %>
          </li>
        <% end %>
        <li>
        <%= link_to "Home", posts_path %>
        </li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

HackerNewsApp/app/views/posts/index.html.erb
<ul>
  <% @posts.each do |post| %>
  <li>
    <p><a href="<%= post.url %>"><%= post.title %></a> by <%= post.user.username %></p>
  </li>
  <% end %>
</ul>

<% if logged_in? %>
  <%= link_to 'Create New Post', new_post_path %>
<% end %>

HackerNewsApp/app/views/posts/new.html.erb
<%= form_for ([current_user, current_user.posts.build]) do |f|  %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <p>
        <%= msg %>
      </p>
    <% end %>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit "Create Post" %>
<% end %>

HackerNewsApp/app/views/users/login.html.erb
<% if @password_error %>
  <p>
    Please enter correct password
  </p>
<% end %>

<% if @username_error %>
  <p>
    Please enter a valid username
  </p>
<% end %>

<%= form_for :user, url: loginn_path do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit "Login" %>
  </p>
<% end %>

HackerNewsApp/app/views/users/new.html.erb
<% if @user.errors %>
  <% @user.errors.full_messages.each do |error| %>
    <p>
      <%= error %>
    </p>
  <% end %>
<% end %>

<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit "Register" %>
  </p>
<% end %>

HackerNewsApp/app/views/users/show.html.erb
<p>
  Show user's posts
</p>